Install missing stomper
  File "/usr/local/lib/python3.12/site-packages/moksha/hub/stomp/stomp.py", line 108, in buildProtocol
    self.proto = StompProtocol(self, self.username, self.password)
  File "/usr/local/lib/python3.12/site-packages/moksha/hub/stomp/protocol.py", line 52, in __init__
    stomper.Engine.__init__(self)
builtins.NameError: name 'stomper' is not defined

pip-compile -P 'stomper==0.4.3' requirements.in --output-file requirements.txt