actions: temporarily switch to new image
apx was missing despite of httpd-devel was mentioned in PR.
because dependencies were not installed from PR but from base image

        File "/tmp/pip-build-env-lurmtz26/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 88, in <module>
      RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.
      [end of output]