Pin yarl version to >= 1.9.2
aiohttp is uninstallable with Python 3.11, but this should be fixed in
aiohttp 3.8.3 (which installs yarl >= 1.9.2), however the yarl in the
generated requirements.txt is 1.7.2 which will cause problem of:

      aiohttp/_websocket.c:198:12: fatal error: longintrepr.h: No such file or directory
        198 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

so pin yarl version in requirements.in to workaround this.