Install missign service-identity
There are warnigns:
bash-5.1(freshmaker)$ oc logs pod/freshmaker-prod-consumer-177-bns57 -c consumers | grep WARN
{"asctime": "2026-07-23 07:14:37", "name": "moksha.hub", "levelname": "WARNING", "message": "Cannot find qpid python module. Make sure you have python-qpid installed.", "taskName": null}
{"asctime": "2026-07-23 07:14:37", "name": "moksha.hub", "levelname": "WARNING", "message": "Connecting without SNI support due to absence of service_identity module.", "taskName": null}

sh-5.2$ rpm -q python3-service-identity
python3-service-identity-23.1.0-3.fc39.noarch
sh-5.2$ rpm -e python3-service-identity
error: Failed dependencies:
        python3.12dist(service-identity) >= 18.1 is needed by (installed) python3-twisted+tls-23.10.0-1.fc39.noarch

pip-compile -P 'twisted==23.10.0' -P 'service-identity==23.1.0' requirements.in --output-file requirements.txt